apiVersion: v1
kind: Secret
metadata:
  name: keycloak-env
  namespace: zerotrust
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: Admin123!
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgres:5432/appdb
  KC_DB_USERNAME: appuser
  KC_DB_PASSWORD: postgres
