# Paramètres réseau et kernel pour améliorer la sécurité
net.ipv4.ip_forward = 0          # Empêche le routage IP non voulu
net.ipv4.conf.all.rp_filter = 1  # Active Reverse Path Filtering
net.ipv4.conf.default.rp_filter = 1
